export const translateSupabaseError = (errorCode: string): string => {
  const errors: { [key: string]: string } = {
    'anonymous_provider_disabled': 'Login anônimo está desativado.',
    'bad_code_verifier': 'Erro de verificação de código. Tente novamente.',
    'bad_json': 'O corpo da requisição não é um JSON válido.',
    'bad_jwt': 'Token de autenticação inválido.',
    'bad_oauth_callback': 'Erro no callback de autenticação. Tente novamente.',
    'bad_oauth_state': 'Estado da autenticação inválido. Tente novamente.',
    'captcha_failed': 'Falha na verificação do CAPTCHA.',
    'conflict': 'Conflito de dados. Tente novamente mais tarde.',
    'email_address_invalid': 'Endereço de email inválido.',
    'email_address_not_authorized': 'Email não autorizado.',
    'email_conflict_identity_not_deletable': 'Não é possível desvincular este email.',
    'email_exists': 'Este email já está cadastrado.',
    'email_not_confirmed': 'Email não confirmado. Verifique sua caixa de entrada.',
    'email_provider_disabled': 'Cadastro com email e senha desativado.',
    'flow_state_expired': 'Sessão expirada. Faça login novamente.',
    'flow_state_not_found': 'Sessão não encontrada. Faça login novamente.',
    'hook_payload_invalid_content_type': 'Erro interno: Tipo de conteúdo inválido.',
    'hook_payload_over_size_limit': 'Erro interno: Payload muito grande.',
    'hook_timeout': 'Tempo limite excedido. Tente novamente.',
    'hook_timeout_after_retry': 'Tempo limite excedido após tentativas.',
    'identity_already_exists': 'Esta conta já está vinculada a outro usuário.',
    'identity_not_found': 'Conta não encontrada.',
    'insufficient_aal': 'Autenticação de dois fatores necessária.',
    'invalid_credentials': 'Email ou senha incorretos.',
    'invite_not_found': 'Convite expirado ou não encontrado.',
    'manual_linking_disabled': 'Vinculação manual desativada.',
    'mfa_challenge_expired': 'Desafio MFA expirado. Solicite um novo.',
    'mfa_factor_name_conflict': 'Nome do fator MFA já existe.',
    'mfa_factor_not_found': 'Fator MFA não encontrado.',
    'mfa_ip_address_mismatch': 'Endereço IP incompatível para MFA.',
    'mfa_phone_enroll_not_enabled': 'Cadastro de MFA por telefone desativado.',
    'mfa_phone_verify_not_enabled': 'Verificação de MFA por telefone desativada.',
    'mfa_totp_enroll_not_enabled': 'Cadastro de MFA TOTP desativado.',
    'mfa_totp_verify_not_enabled': 'Verificação de MFA TOTP desativada.',
    'mfa_verification_failed': 'Código MFA incorreto.',
    'mfa_verification_rejected': 'Verificação MFA rejeitada.',
    'mfa_verified_factor_exists': 'Fator MFA já verificado.',
    'mfa_web_authn_enroll_not_enabled': 'Cadastro de WebAuthn desativado.',
    'mfa_web_authn_verify_not_enabled': 'Verificação de WebAuthn desativada.',
    'no_authorization': 'Autorização necessária.',
    'not_admin': 'Acesso negado. Requer privilégios de administrador.',
    'oauth_provider_not_supported': 'Provedor de login não suportado.',
    'otp_disabled': 'Login com OTP desativado.',
    'otp_expired': 'Código expirado. Solicite um novo.',
    'over_email_send_rate_limit': 'Muitos emails enviados. Aguarde um momento.',
    'over_request_rate_limit': 'Muitas requisições. Tente novamente mais tarde.',
    'over_sms_send_rate_limit': 'Muitos SMS enviados. Aguarde um momento.',
    'phone_exists': 'Telefone já cadastrado.',
    'phone_not_confirmed': 'Telefone não confirmado.',
    'phone_provider_disabled': 'Cadastro com telefone desativado.',
    'provider_disabled': 'Provedor de login desativado.',
    'provider_email_needs_verification': 'Email precisa ser verificado.',
    'reauthentication_needed': 'Reautenticação necessária.',
    'reauthentication_not_valid': 'Reautenticação falhou.',
    'refresh_token_already_used': 'Sessão inválida. Faça login novamente.',
    'refresh_token_not_found': 'Sessão não encontrada. Faça login novamente.',
    'request_timeout': 'Tempo limite excedido. Tente novamente.',
    'same_password': 'A nova senha deve ser diferente da atual.',
    'saml_assertion_no_email': 'Erro SAML: Email não encontrado.',
    'saml_assertion_no_user_id': 'Erro SAML: ID de usuário não encontrado.',
    'saml_entity_id_mismatch': 'Erro SAML: ID da entidade incompatível.',
    'saml_idp_already_exists': 'Provedor de identidade já existe.',
    'saml_idp_not_found': 'Provedor de identidade não encontrado.',
    'saml_metadata_fetch_failed': 'Falha ao buscar metadados SAML.',
    'saml_provider_disabled': 'Login SAML desativado.',
    'saml_relay_state_expired': 'Estado SAML expirado.',
    'saml_relay_state_not_found': 'Estado SAML não encontrado.',
    'session_expired': 'Sessão expirada. Faça login novamente.',
    'session_not_found': 'Sessão não encontrada.',
    'signup_disabled': 'Novos cadastros estão desativados.',
    'single_identity_not_deletable': 'Não é possível remover a única forma de login.',
    'sms_send_failed': 'Falha ao enviar SMS.',
    'sso_domain_already_exists': 'Domínio SSO já registrado.',
    'sso_provider_not_found': 'Provedor SSO não encontrado.',
    'too_many_enrolled_mfa_factors': 'Muitos fatores MFA cadastrados.',
    'unexpected_audience': 'Erro de autenticação: Audiência inesperada.',
    'unexpected_failure': 'Erro inesperado. Tente novamente.',
    'user_already_exists': 'Usuário já cadastrado.',
    'user_banned': 'Usuário banido.',
    'user_not_found': 'Usuário não encontrado.',
    'user_sso_managed': 'Usuário gerenciado por SSO.',
    'validation_failed': 'Dados inválidos.',
    'weak_password': 'Senha muito fraca.',
  };

  return errors[errorCode] || 'Ocorreu um erro desconhecido.';
};
